### ISSUE TITLE
toto sa stane keď spustím

### ISSUE THREAD

**Issue by matej172** [erichstark/fei-web-validator#1]
C:\Users\matej-work\Downloads\fei-web-validator-master\index.js:25
    files.forEach(function(file) {
         ^

TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\matej-work\Downloads\fei-web-validator-master\index.js:25:10
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by erichstark** [comment]
Spustas to ako `node index.js moodle > file.txt` ?
Cize priecinok moodle by mal byt v tvojom pripade v zlozke Downloads a v nom vsetky tie .zip subory.

**Comment by erichstark** [comment]
Je to ok.
